spring:
  application:
    name: gateway

  cloud:
    config:
      discovery:
        enabled: true

    gateway:
      discovery.locator.enabled: true
      routes:
        - id: shopping_cart_route
          uri: lb://shopping-cart
          predicates:
            - Path=/shopping-cart/**
          filters:
            - name: RewritePath
              args:
                regexp: "/shopping-cart/(?<segment>.*)"
                replacement: "/api/v1/shopping-cart/${segment}"
            - name: Retry
              args:
                retries: 3
                statuses:
                  - NOT_FOUND
                backoff:
                  firstBackoff: 1s
                  maxBackoff: 5s
                  factor: 2

        - id: shopping-store-route
          uri: lb://shopping-store
          predicates:
            - Path=/shopping-store/**
          filters:
            - name: RewritePath
              args:
                regexp: "/shopping-store/(?<segment>.*)"
                replacement: "/api/v1/shopping-store/${segment}"
            - name: Retry
              args:
                retries: 3
                statuses:
                  - NOT_FOUND
                backoff:
                  firstBackoff: 1s
                  maxBackoff: 5s
                  factor: 2

        - id: warehouse-route
          uri: lb://warehouse
          predicates:
            - Path=/warehouse/**
          filters:
            - name: RewritePath
              args:
                regexp: "/warehouse/(?<segment>.*)"
                replacement: "/api/v1/warehouse/${segment}"
            - name: Retry
              args:
                retries: 3
                statuses:
                  - NOT_FOUND
                backoff:
                  firstBackoff: 1s
                  maxBackoff: 5s
                  factor: 2

        - id: delivery-route
          uri: lb://delivery
          predicates:
            - Path=/delivery/**
          filters:
            - name: RewritePath
              args:
                regexp: "/delivery/(?<segment>.*)"
                replacement: "/api/v1/delivery/${segment}"
            - name: Retry
              args:
                retries: 3
                statuses:
                  - NOT_FOUND
                backoff:
                  firstBackoff: 1s
                  maxBackoff: 5s
                  factor: 2

        - id: order-route
          uri: lb://order
          predicates:
            - Path=/order/**
          filters:
            - name: RewritePath
              args:
                regexp: "/order/(?<segment>.*)"
                replacement: "/api/v1/order/${segment}"
            - name: Retry
              args:
                retries: 3
                statuses:
                  - NOT_FOUND
                backoff:
                  firstBackoff: 1s
                  maxBackoff: 5s
                  factor: 2

        - id: payment-route
          uri: lb://payment
          predicates:
            - Path=/payment/**
          filters:
            - name: RewritePath
              args:
                regexp: "/payment/(?<segment>.*)"
                replacement: "/api/v1/payment/${segment}"
            - name: Retry
              args:
                retries: 3
                statuses:
                  - NOT_FOUND
                backoff:
                  firstBackoff: 1s
                  maxBackoff: 5s
                  factor: 2